name: Pull Request Quality Checks
on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
jobs:
  run-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
      - name: Run qa
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          make dev
          make qa
