name: Pull Request Quality Checks
on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
jobs:
  run-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.11
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
      - name: Run qa
        run: |
          python_loc="$(which python || true)"
          echo "python location: $python_loc"
          echo "python --version $(python --version || true)"
          python -m venv ./.venv
          source ./.venv/bin/activate
          echo "Running uv sync --all-extras --no-cache"
          uv sync --all-extras --no-cache
          echo "uv sync complete!"
          echo "Checking for ruff before running qa..."
          ruff_loc="$(which ruff || true)"
          echo "ruff located at $ruff_loc"
          ruff_installation="$(pip show ruff || true)"
          echo "ruff installation: "
          echo "$ruff_installation"
          make qa
